license_id: cc-by
methodology: Other
methodology_other: |
  [Methodology (RTFP)](https://microdata.worldbank.org/index.php/catalog/4483/pdf-documentation)
  [Data Schema (RTFP)](https://microdata.worldbank.org/index.php/catalog/4483/data-dictionary/WLD_2021_RTFP_MKT?file_name=WLD_RTFP_mkt_2025-08-11.csv)
caveats:
dataset_source: World Bank
package_creator: HDX Data Systems Team
private: False
maintainer: fdbb8e79-f020-4039-ab3a-9adb482273b8 # erikawei
owner_org: 905a9a49-5325-4a31-a9d7-147a60a8387c # worldbank
data_update_frequency: 7
notes: RTP includes three sub-series, Real Time Food Prices (RTFP) includes prices on a variety of food items that primarily include country-specific staple foods, Real Time Energy Prices (RTEP) includes fuel prices, and Real Time Exchange Rates (RTFX) and includes unofficial exchange rate estimates as well as possible other unofficial deflators.
